services:
    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments:
            - ~
            - AppBundle\Entity\Post
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Posts"
              label: "Post"
        public: true